services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    # restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'Welkom01!'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_database'] = 'gitlabhq_production'
        gitlab_rails['db_pool'] = 10
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab'
        gitlab_rails['db_host'] = 'gitlab_postgresql_database'
        gitlab_rails['db_port'] = 5432
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    depends_on:
      - gitlab_postgresql_database
    networks:
      - gitlab_network

  gitlab_postgresql_database:
    image: postgres:latest
    container_name: gitlab_postgresql_database
    # restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlabhq_production
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge
